document.writeln("  <div id=\'mySidebar\' class=\'ui left sidebar inverted vertical accordion menu\'>");
document.writeln("    <div class=\'item\'>");
document.writeln("      <a class=\'title\'>");
document.writeln("        <i class=\'dropdown icon\'></i>");
document.writeln("        <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj3_front.html\')\">上海市质量可视化展图</span> ");
document.writeln("      </a>");
document.writeln("      <div class=\'content\'>");
document.writeln("        <div class=\'inverted vertical accordion\'>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <i class=\'dropdown icon\'></i>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'index_2.html\')\">页面2</span> ");
document.writeln("            </a>");
document.writeln("            <div class=\'content\'>");
document.writeln("              <div class=\'inverted vertical accordion\'>");
document.writeln("                <div class=\'item\'>");
document.writeln("                  <a class=\'title\'>");
document.writeln("                    <!-- <i class=\'dropdown icon\'></i> -->");
document.writeln("                    <span class=\'sidebar_item\' onclick=\"relinkTo(\'index_3.html\')\">页面3</span> ");
document.writeln("                  </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'item\'>");
document.writeln("                  <a class=\'title\'>");
document.writeln("                    <!-- <i class=\'dropdown icon\'></i> -->");
document.writeln("                    <span class=\'sidebar_item\' onclick=\"relinkTo(\'index_10.html\')\">页面10</span> ");
document.writeln("                  </a>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'index_4.html\')\">页面4</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'index_5.html\')\">页面5</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <i class=\'dropdown icon\'></i>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'index_6.html\')\">页面6</span> ");
document.writeln("            </a>");
document.writeln("            <div class=\'content\'>");
document.writeln("              <div class=\'inverted vertical accordion\'>");
document.writeln("                <div class=\'item\'>");
document.writeln("                  <a class=\'title\'>");
document.writeln("                    <!-- <i class=\'dropdown icon\'></i> -->");
document.writeln("                    <span class=\'sidebar_item\' onclick=\"relinkTo(\'index_11.html\')\">页面11</span> ");
document.writeln("                  </a>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'index_7.html\')\">页面7</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'index_8.html\')\">页面8</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'index_9.html\')\">页面9</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\'item\'>");
document.writeln("      <a class=\'title\'>");
document.writeln("        <i class=\'dropdown icon\'></i>");
document.writeln("        <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj4_front.html\')\">宏观经济数据</span> ");
document.writeln("      </a>");
document.writeln("      <div class=\'content\'>");
document.writeln("        <div class=\'inverted vertical accordion\'>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <!-- <i class=\'dropdown icon\'></i> -->");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj4_1.html\')\">国家优质制造水平评价数据</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj4_2.html\')\">世界500强排行榜数据</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj4_3.html\')\">企业相关指数数据</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <!-- <i class=\'dropdown icon\'></i> -->");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj4_4.html\')\">年度质量抽查及投诉数据</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj4_5.html\')\">高端装备制造业分行业评价数据</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj4_6.html\')\">中国与世界国民经济数据</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\'item\'>");
document.writeln("      <a class=\'title\'>");
document.writeln("        <i class=\'dropdown icon\'></i>");
document.writeln("        <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj5_front.html\')\">行业质量数据</span> ");
document.writeln("      </a>");
document.writeln("      <div class=\'content\'>");
document.writeln("        <div class=\'inverted vertical accordion\'>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <!-- <i class=\'dropdown icon\'></i> -->");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj5_1.html\')\">船舶行业</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj5_2.html\')\">汽车行业</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj5_3.html\')\">航天行业</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <!-- <i class=\'dropdown icon\'></i> -->");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj5_4.html\')\">医械行业</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj5_5.html\')\">机床产业</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'item\'>");
document.writeln("            <a class=\'title\'>");
document.writeln("              <span class=\'sidebar_item\' onclick=\"relinkTo(\'pj5_front.html\')\">海洋重工</span> ");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    ");
document.writeln("  </div>");
document.writeln("  <div class=\'pusher\' style=\'height: 100%; margin: 0\'>");
document.writeln("    <div id=\'app\'></div>");
document.writeln("  </div>");


$('<i id="back-to-top" style="z-index: 999;" onclick="history.back()"></i>').appendTo($('.pusher'));
$('#back-to-top').fadeIn();	

$('<i id="pop-sidebar" style="z-index: 999;" onclick="$(\'.ui.sidebar\').sidebar(\'toggle\');"></i>').appendTo($('.pusher'));
$('#pop-sidebar').fadeIn();	

$("#next").show();

$('.ui.accordion').accordion();


function relinkTo(desSrc){
    console.log(desSrc)
    window.location.href="../total_frame.html?noticeId="+desSrc;
}

